### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Nytelife26** [rovelstars/rovel.js#5]
...what is this?

"The awesome package with fully packed features for every developer on earth" is the most ambiguous description I've ever read.

And the README doesn't help either. The description and docs should come long before you talk about how to install things. How do people know what they're installing otherwise?

You should probably consider clarifying and fixing these.

**Comment by sayantan300** [comment]
I know I have to make docs, but I was busy studying because my school exams are starting, also I'm working on many different projects alongside rovel.js so it will take time to make docs. Also I'm going to get a new domain, so I need to transfer all my projects to the new domain soon. Hope you understand my problem 😅

**Comment by Nytelife26** [comment]
I mean, yes, but also no. The parts that have been written don't cover anything. The description isn't a description, it's a series of buzzwords, and the README is poorly formatted. I genuinely have no idea what this project is for and I was asking for that reason

**Comment by sayantan300** [comment]
Ok, I will try to add some docs for it. Kindly check https://rovelstars.ga tomorrow 😄
